# Use nvidia/cuda image
FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

# Ignore interactive questions during `docker build`
ENV DEBIAN_FRONTEND noninteractive

RUN python -m pip install onnx onnxruntime
RUN python -m pip install debugpy
RUN python -m pip install onnx_graphsurgeon --index-url https://pypi.ngc.nvidia.com

WORKDIR .

# Bash shell
RUN chsh -s /bin/bash
SHELL ["/bin/bash", "-c"]

CMD ["/bin/bash"]
